rm(list=ls()) #clean, clc, close all
# ***************
# R version 4.4.2 / win
# author: Nikola Jordánová
# *************

# Path
setwd('V:/MPA-PRG/exercise_06') # set working directory

install.packages("gtools")
library(gtools)

# Task 1
DoubleDigestProblem <- function(fragments_A, fragments_B, fragments_AB){
  # fragments_A - A multiset of fragments generated by digestion by enzyme A
  # fragments_B - A multiset of fragments generated by digestion by enzyme B
  # fragments_AB - A multiset of fragments generated by digestion by enzymes A + B
  
  perms_A <- permutations(n=length(fragments_A), r=length(fragments_A), v=fragments_A)
  perms_B <- permutations(n=length(fragments_B), r=length(fragments_B), v=fragments_B)
  
  correct_solutions <- list()

  
  for (i in 1:nrow(perms_A)) {
    for (j in 1:nrow(perms_B)) {
      perm_A <- perms_A[i, ]
      perm_B <- perms_B[j, ]
  
      positions_A <- c(0,cumsum(perm_A))
      positions_B <- c(0,cumsum(perm_B))
  
      combined_positions <- sort(unique(unlist(c(positions_A, positions_B))))
  
      successive_differences <- sort(diff(combined_positions))
      
      if (all(successive_differences == fragments_AB)){
        positions_A <- positions_A[2:(length(positions_A) - 1)]
        positions_B <- positions_B[2:(length(positions_B) - 1)]
        correct_solutions[[length(correct_solutions) + 1]] <- list(
          positions_A = positions_A,
          positions_B = positions_B
        )
        
      } 

    }
  }
  return(correct_solutions)
}

A <- c(2,3,5,10)
B <- c(3,7,10)
AB <- c(1,2,2,5,5,5)
DoubleDigestProblem(A, B, AB)


# Task 2
Remove <- function(deltaX, deltas) {
  for (d in deltas) {
    i <- match(d, deltaX)
    if (!is.na(i)) {
      deltaX <- deltaX[-i]
    }
  }
  return(deltaX)
}


Place <- function(deltaX, X, width){
   if (length(deltaX == 0)){
     return (X)
   }
   y <- max(deltaX)
   deltas <- abs(X-y)
   if (all(table(deltas) <= table(deltaX)[as.character(deltas)])){
     X <- c(X, y)
     deltaX <- Remove(deltaX, deltas)
     Place(deltaX, X, width)
     # remove y from X and add the lengths Δ(y, X) to deltaX
   }
   
   y_mirror <- width - y
   deltas_mirror <- abs(y_mirror - X)
   if (all(table(deltas_mirror) <= table(deltaX)[as.character(deltas_mirror)])) {
     deltaX_new <- Remove(deltaX, deltas_mirror)
     X_new <- c(X, y_mirror)
     Place(deltaX_new, X_new, width)
   }
  return ()

}


deltaX <- c(2,2,3,3,4,5,6,7,8,10)
X <- c()
width <- 10

Place(deltaX, X, width)
