rm(list=ls()) #clean, clc, close all
# ***************
# R version 4.4.2 / win
# author: Nikola Jordánová
# *************

# Path
#setwd('V:/MPA-PRG/exercise_06') # set working directory
setwd('C:/Users/nikol/School/MPA-PRG/exercise_06')

install.packages("gtools")
library(gtools)

# Task 1
DoubleDigestProblem <- function(fragments_A, fragments_B, fragments_AB){
  # fragments_A - A multiset of fragments generated by digestion by enzyme A
  # fragments_B - A multiset of fragments generated by digestion by enzyme B
  # fragments_AB - A multiset of fragments generated by digestion by enzymes A + B
  
  # Všechny možné kombinace fragmentů A a B
  perms_A <- permutations(n=length(fragments_A), r=length(fragments_A), v=fragments_A)
  perms_B <- permutations(n=length(fragments_B), r=length(fragments_B), v=fragments_B)
  
  # List pro správné výsledky
  correct_solutions <- list()

  # Procházení jednotlivých kombinací
  for (i in 1:nrow(perms_A)) { 
    for (j in 1:nrow(perms_B)) {
      perm_A <- perms_A[i, ]
      perm_B <- perms_B[j, ]
  
      # Převod fragmentů na pozice
      positions_A <- c(0,cumsum(perm_A))
      positions_B <- c(0,cumsum(perm_B))
  
      # Zkombinování pozic
      combined_positions <- sort(unique(unlist(c(positions_A, positions_B))))
  
      # Rozdíly - délky fragmentů, které vzniknou kombinací A a B
      successive_differences <- sort(diff(combined_positions))
      
      # Pokud se rozdílky shodují s původním
      if (all(successive_differences == fragments_AB)){
        # Pozice bereme bez nuly a posledního čísla
        positions_A <- positions_A[2:(length(positions_A) - 1)]
        positions_B <- positions_B[2:(length(positions_B) - 1)]
        # Přidáme nakonec listu
        correct_solutions[[length(correct_solutions) + 1]] <- list(
          positions_A = positions_A,
          positions_B = positions_B
        )
        
      } 

    }
  }
  return(correct_solutions)
}

A <- c(2,3,5,10)
B <- c(3,7,10)
AB <- c(1,2,2,5,5,5)
DoubleDigestProblem(A, B, AB)


# Task 2
Remove <- function(deltaX, deltas) {
  # Funkce vezme vektor deltaX a odstraní z něj všechny prvky, které se nachází ve vektoru deltas
  for (d in deltas) {
    i <- match(d, deltaX) # index první shody d v deltaX
    # Pokud prvek existuje, odstraníme jej z deltaX
    if (!is.na(i)) {
      deltaX <- deltaX[-i]
    }
  else {
    # pokud délka chybí, neplatný krok
    return(NULL)
  }
  }
  return(deltaX)
}


Place <- function(deltaX, X, width){
  # deltaX - multiset of fragments lengths
  # X - list of the current positions of the restriction sites
  # width - length of the DNA molecule i.e. the size of the longest fragment
  
  # Pokud je deltaX prázdné, tak srovnej X a vrať
   if (length(deltaX) == 0){
     return (sort(X))
   }
  
  # Nalezení maximální hodnoty
   y <- max(deltaX)
   
   # Zkus umístit y - první větev
   deltas <- abs(X-y)
   deltaX_new <- Remove(deltaX, deltas)
   
   
   if (!is.null(deltaX_new) && !(y %in% X)) { # všechny vzdálenosti existují v deltaX a není to duplicitní bod
     # přidej y do X
     X_new <- c(X, y)
     # rekurze
     result <- Place(deltaX_new, X_new, width)
     if (!is.null(result)){
       return(result)
     }
     # 8. remove y from X and add Δ(y, X) back to deltaX (automaticky vráceno)
   }
   
   # Druhá větev
   y_mirror <- width - y
   deltas_mirror <- abs(X - y_mirror)
   deltaX_new2 <- Remove(deltaX, deltas_mirror)
   
   if (!is.null(deltaX_new2) && !(y_mirror %in% X)) {
     X_new2 <- c(X, y_mirror)
     result <- Place(deltaX_new2, X_new2, width)
     if (!is.null(result)) {
       return(result)
     }
   }
   
   # Pokud nic nevyšlo, vrať NULL (žádné řešení)
   return(NULL)

}


deltaX <- c(5,7,8,12,15,20)
width <- 20
X <- c(0)
Place(deltaX, X, width)

PartialDigestProblem <- function(deltaX) {
  # 1. width = maximum prvek deltaX
  width <- max(deltaX)
  
  # 2. odstraň maximum z deltaX
  deltaX <- Remove(deltaX, width)
  
  # 3. počáteční X = {0, width}
  X <- c(0, width)
  
  # 4. zavolání Place()
  return(Place(deltaX, X, width))
}


PartialDigestProblem(c(5,7,8,12,15,20))



